# Generated by Django 2.0.5 on 2018-06-04 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChattingRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_content', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'chatting records',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(db_column='class_ID', primary_key=True, serialize=False)),
                ('class_content', models.CharField(db_column='class_ content', max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('hello_id', models.AutoField(db_column='hello_ID', primary_key=True, serialize=False)),
                ('hello_content', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'hello',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(db_column='question_ID', primary_key=True, serialize=False)),
                ('question_content', models.CharField(max_length=30)),
            ],
            options={
                'managed': False,
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Writings',
            fields=[
                ('writings_id', models.AutoField(db_column='writings_ID', primary_key=True, serialize=False)),
                ('writings_name', models.CharField(max_length=255)),
                ('writings_content', models.TextField(db_column='writings_ content')),
                ('notes', models.CharField(max_length=255)),
                ('image', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'writings',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.ForeignKey(db_column='user_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='closer.ChattingRecords')),
                ('user_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=2)),
                ('image', models.TextField()),
                ('email', models.CharField(max_length=20, unique=True)),
                ('facebook_user', models.CharField(max_length=20, unique=True)),
                ('google_user', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'users',
            },
        ),
    ]
